---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking-external-services
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/networking/external-services
  sourceRef:
    kind: GitRepository
    name: homelab-kubernetes
  dependsOn:
    - name: traefik-system
    - name: security-onepassword-connect
  prune: true
  wait: true
  interval: 30m
  retryInterval: 2m
  timeout: 1m
