---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-4k-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 2Gi
