apiVersion: v1
kind: Secret
metadata:
    name: radarr-4k
    namespace: media
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:Wf7tZpvMQZY09PUQ0ORfP+dFNyMxwT8f5m/xJeFbehA=,iv:MUMATKAa2vpEhfFJ1Bo7QKJbL+x9uwUhbc3ndkPE1v4=,tag:X3AScHsqpvnsza5S7inweA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWG1WSTZ5ekJkRSs2MlMz
            MTg0SVdzbDVTbW9saWptVnNyaW5WVkhWTEE0CjlGUWJLanV0Qlp6dFlaRHZXWDdE
            dnlDODhNSVlEYS94WEY2OTNOc2Nuc0EKLS0tIGFWR3ZXZjJOYkdEeXFYQ1M4WVJY
            eDU3d2tMeEoyaFNwN3I0TFY3TUUwNlUKH13Fq2Xpa3m7ieSJoD8Ij8Fu6YEtgtZA
            ZJWawnDcbBs4kjfyVSpcoZW9jIlJNmUBCA2WceRf52sxZsHtai+T8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-25T01:36:19Z"
    mac: ENC[AES256_GCM,data:H4Rv7CT13UvMuSSCq1UqWC/FfB688bWChl86y9W6zfCpAiUhbAK6j04hSUcvMX1ztfe+zRJwDJJVS5pna2Yq5lqgJg3De/dVGHr4GQthyptEqOxCXyOURapuru8JWaOFoOlQow5Jgfc7ZT9t5MUJiKSygwjGDq/VSKexGuzZ4Cc=,iv:1r5v1zzxakwtxonsmEEwu5cDz1oCMofZz19ln/lSOdw=,tag:1l6sI2as/9cR07lLSk3dmQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
