---
cluster:
  name: "${CONFIG_CLUSTER_NAME}"
  id: "1"

securityContext:
  privileged: true

kubeProxyReplacement: "strict"
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
k8sServiceHost: "${CONFIG_CLUSTER_NAME}.${SECRET_BASE_DOMAIN_NAME}"
k8sServicePort: 6443

ipv4NativeRoutingCIDR: "${CONFIG_K8S_POD_CIDR}"

ipam:
  mode: "kubernetes"

containerRuntime:
  integration: containerd

hubble:
  enabled: false

ipv6:
  # -- Enable IPv6 support.
  enabled: false
