---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline-secrets
  namespace: web-tools
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: outline
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
  dataFrom:
    - extract:
        key: outline
