---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik-system
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/traefik-system/traefik-system/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: traefik
      namespace: traefik-system
  interval: 30m
  retryInterval: 2m
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik-system-add-ons
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: cert-manager
    - name: traefik-system
  path: ./kubernetes/apps/traefik-system/traefik-system/add-ons
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-kubernetes
  healthChecks:
    - apiVersion: traefik.containo.us/v1alpha1
      kind: TLSStore
      name: default
      namespace: traefik-system
  interval: 30m
  retryInterval: 2m
  timeout: 1m
