---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app excalidraw
  namespace: web-tools
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
      rollingUpdate:
        unavailable: 2
        surge: 0
    image:
      repository: docker.io/excalidraw/excalidraw
      tag: latest@sha256:352d4025404bd9f95bdfff379b74eb1a792d20491b1bba71eb978cd390253bc0
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-system-external-auth@kubernetescrd"
          external-dns.alpha.kubernetes.io/target: "${SECRET_DOMAIN_NAME}"
          external-dns/is-public: "true"
        hosts:
          - host: "draw.${SECRET_DOMAIN_NAME}"
            paths:
              - path: /
                pathType: Prefix
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        memory: 50Mi
