---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/kyverno/kyverno/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: kyverno
      namespace: kyverno
  interval: 30m
  retryInterval: 2m
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/kyverno/kyverno/policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-kubernetes
  interval: 30m
  retryInterval: 2m
  timeout: 1m
