apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ADMIN_NAME: ENC[AES256_GCM,data:j51W7I4L,iv:5XHD790nm3dEkkywYlrl5b6Ovv1xZ+vSQfurT+ue2Hw=,tag:oaGfayadyGwJ5d8puYSFyQ==,type:str]
    SECRET_ADMIN_EMAIL: ENC[AES256_GCM,data:raPlmy7DGTSnqEFLwzw=,iv:bINXywjb3eo9fqL75rgDx4dZa+Sth59TF23CTvAUREw=,tag:LhkrUI2aI0tF6jdIyVMSbQ==,type:str]
    SECRET_DOMAIN_NAME: ENC[AES256_GCM,data:+HkxvRZtEg==,iv:ac/aahNmYcI08MbdOFQuUcnUJ+AhVO9GUKGjoS9/W0M=,tag:veRkBpG9qA5SN/Vd09BHHw==,type:str]
    SECRET_BASE_DOMAIN_NAME: ENC[AES256_GCM,data:rZq/dkcsng==,iv:14vGefDv5WOqUA6ZJSTQ5YAflGxKbJMfNw+IaxlGW18=,tag:ZIJ7jQJzzj+KbUuUv97Xbw==,type:str]
    SECRET_NFS_SERVER: ENC[AES256_GCM,data:wn+xgcjU//OK4doqqg==,iv:DQ7N/+/0yBV+rXZACR7thQy6d+OFSZZxoF5mrVboOQM=,tag:joIM09V1NVES5qSUm3byqw==,type:str]
    SECRET_NFS_ROOTDIR: ENC[AES256_GCM,data:1OnfdqgMONJBXQK/ozXxRVE=,iv:SD8VLD4SDjZIGSMmuONVhjcTgslLg96bnbDNzMsrhjg=,tag:Xy62QiyCB9deX1I2L8hw9A==,type:str]
    SECRET_ATLAS_NFS_SERVER: ENC[AES256_GCM,data:drU9Dq3Hfjr9T+8cKAc=,iv:Jt6uEnyRD92EKHQ5ksui3xssxLPB6hsh4anVOqbgskE=,tag:pWH4OafrNzGXq+NEw37vug==,type:str]
    SECRET_ATLAS_NFS_ROOTDIR: ENC[AES256_GCM,data:dMcFzfhuLNdt6DHsvvF55H3r3w==,iv:uKcxdQynEr+p9WTGJwmGRLb1P31oVEsfylRYKFttGw8=,tag:ZBVon3NCaAvpXCkJ53uxvQ==,type:str]
    SECRET_NFS_MEDIA_DIR: ENC[AES256_GCM,data:Pc26lPtBTBKRULZsCQ==,iv:mdR/9XLrAFU8VBLEHnrTzkzRYLliJc79Tf7Nzdqo7zc=,tag:27QT5HxfGJrnvwV+5OglWA==,type:str]
    TESLAMATE_ENCRYPTION_KEY: ENC[AES256_GCM,data:DlcNePVbuYBn+tb/u25SG30nRje3gS8YQrudz/4sKwuhOPmh5gqOAcztoRZBjWHuUmywI1yCm/e4,iv:549K+9umnoDmfKM8IUk8J4zT9eTibyV6OWsewpmrt8I=,tag:PnoSmWOKuouNwAzEMNtagQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eDBGcUFvdFVuV2NINW8r
            NjU0YWFObTYvWVFwWWp4T0NMQkNrbVFQWFFNCnphL251RHppQmcxc3dkamVTNlg1
            bDlub1paa1N6VHJ4dmpieE9Zd0hZR0EKLS0tIFBoWFBTWVJkbWpuQllFR01iNG9D
            OUtETHBDRjJ6Q2IvU0swZDVmaTBtN3cK2J8PasNRATIFo7RifrLuVyKdx4R0PhI6
            FIT70uAcafGJKcs2lBT+1t9Ucr1NngEjdeOJLfjAUQmxgDnnMl57mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-17T10:27:05Z"
    mac: ENC[AES256_GCM,data:cKKf91bsgrZoGWuvVO6OHPMZpl3fNEkEDjtWbAir34UFm4EGV8yI8hL9KggsH9tqjoK3j919w5RwXfcMPP8b8S6RNVaU72gGhMhXWY01J3ek1UhkDvLCnoiSYx98SlsBrxI7hgr1g1pZSGryfs4ZGLbEfPJqiK6YmN4bz7Ud6ZE=,iv:Agh1brS17HVg78jejUW46Q8t4yQoFMdaEr9Di5loSx0=,tag:KzQ4hp9Imh4WB+K7cm1F6A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
