apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ADMIN_EMAIL: ENC[AES256_GCM,data:+iElq010HjPXcoy0CBY=,iv:vwcNJszx4zM3SwbFEXeMtTAa+g0+OPNHfAh5MJtlWvk=,tag:srl73Qef87k5Pq+ZHHDI3g==,type:str]
    SECRET_DOMAIN_NAME: ENC[AES256_GCM,data:xqX8E05Dlw==,iv:GbvlRnOHsqt25M1EN8W7wXDmIJ2MK3nUaySwK1etF0k=,tag:JRqIAHFEtmFnV3LzK8LDvg==,type:str]
    SECRET_NFS_SERVER: ENC[AES256_GCM,data:x5ifW3Lu2EOMtQMT9g==,iv:xryN7vubuaZtwQyol9J4eyrrhs/fOwtBl1hAZ5BD3kw=,tag:cd7rDVh5KUBjdCJeBBzGAA==,type:str]
    SECRET_NFS_ROOTDIR: ENC[AES256_GCM,data:DVWHzsfbRxcoawFlhu3yHGU=,iv:wVMKsC75L1VNAyJ/xRTgFojRsVrUbPyhfd40Yk1bACc=,tag:fvNDjy0+g0Hmtt7sx+pR4w==,type:str]
    SECRET_NFS_MEDIA_DIR: ENC[AES256_GCM,data:fkXd/rfLPAf6xo0ffQ==,iv:rgGME+gEgms8Xn0xnU3rHFfPu/b1v9T1VsrIc+vDb7E=,tag:GjWYtxr0uQhy0lI9qRf0eQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OFAyWE5OSjZxamozUGZG
            bUVtS3JhOXpsWnkvSmloN1RudGgyTURCN1g4CjdqcjE1a1FEOW5JYVZLQVNSdHBB
            clNScFdvVXhOQ2syWGRLVGRRM3A5NzQKLS0tIGlkZXBEVjMySWtlMXFLN3JOYnBu
            WnJZQUw0akd2SFlPL2x6WGVvckNLK28K4dxhAWEnlnZbWks+N17h9jMMrCzvjn/4
            aIzbWucRLY0iSBLrvbhMDv4ScTrs1CiMdrc9H2H1sqYOq05gvHsseQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-15T21:02:33Z"
    mac: ENC[AES256_GCM,data:NNgsY0ImG08pks9Cc/MXvNQD8FPgNW96VJLxY2UILufjQcocf7lQ2Q6whM1hQdXuWrsSYLJ8FQJkfJhUBQfykWUhRgwVFp2snaeudQm29FaVQkEZB+V0GxtV5860qH8RZjnGYrLNvtq3xTXb2oZCl3dHI4+zaL2AE9kO0JNSqx0=,iv:He871k+MY9dlSo2QhOP1hRIndqOZWP35yClRxGwQqR4=,tag:MQ0LchNBY91AaQxApQQzDQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.2
