---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kvm-cert
  namespace: envoy-system
spec:
  secretName: kvm-tls
  issuerRef:
    name: ${CONFIG_CERTIFICATE_ISSUER}
    kind: ClusterIssuer
  dnsNames:
    - kvm.${SECRET_DOMAIN_NAME}
