---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: styx-cert
  namespace: envoy-system
spec:
  secretName: styx-tls
  issuerRef:
    name: ${CONFIG_CERTIFICATE_ISSUER}
    kind: ClusterIssuer
  dnsNames:
    - styx.${SECRET_DOMAIN_NAME}
