apiVersion: v1
kind: Secret
metadata:
    name: loki-secrets
    namespace: monitoring
stringData:
    s3-path: ENC[AES256_GCM,data:rH3LXWO4tZlohVnkDBVmaXQEBPV/AyF6h5g7JuXKuOhUgNb7Nxw1yqOLqsS3A+v1ZoQ=,iv:6BMwFBxOOoPnn0ULARXSwiawOckI1d2uv+a1ump+Q48=,tag:igfaUOgUJscYMViWOK4stA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdGVrdnRvcDB5Q0ZtTjRa
            c25JV2N0WnVOSno5TFQvbldGNS9PS3Q4dm04CnZJM0VMbWZYL2sxcStMMDlIcFg3
            OVNWblpBTHFRbmxTemZsMWVQRmlIMVEKLS0tIHBmZTdmdmFpNk92cFU4YzlpU3hI
            Tkd2eGZoN21sYmdtUEpmaFVDRHZrVVEKDmDFr+SrzrumtWBj/q3oF/YESMg5T4hp
            qZm/gurcwfIF7XRz1haY0SubnE9Hj3lW7QclnhPE/+Vn4ir/q+thFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-05T12:41:46Z"
    mac: ENC[AES256_GCM,data:84ElL9v56QZi8+qaLma0eqXSAaPVP3K1F2RBTg1b940SJUCaWU2XMWVjh2XFKyJnbUiR8lHU6yQXeHIF0lC1MCsP/NGOIWqB354Mn1EkpvBz1sOATDV6HIjZu5ZMsa4czLser++VOmOtvzRJXuJlvCMBHttS6UQTePM2OP0Eo3g=,iv:3WItx+UbggijLTc/ldgL2dr3FKzhUvRGN4FYICvqY2s=,tag:EmUlLsCMtMuegxfXz/bbSQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
