---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-pvc
  namespace: media
  labels:
    app.kubernetes.io/name: &name lidarr
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 2Gi
