---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dbms-redis-haproxy
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: dbms-redis
  path: ./kubernetes/apps/dbms/redis-haproxy/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-kubernetes
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: redis-haproxy-deployment
      namespace: dbms
  interval: 30m
  retryInterval: 2m
  timeout: 1m
