---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - actions-runner-controller-charts.yaml
  - authentik-charts.yaml
  - bitnami-charts.yaml
  - deliveryhero-charts.yaml
  - external-dns-charts.yaml
  - fluent-bit-charts.yaml
  - grafana-charts.yaml
  - infracloudio-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  # - kasten-charts.yaml
  - metallb-charts.yaml
  - prometheus-community-charts.yaml
  - rook-ceph-charts.yaml
  - runix-charts.yaml
  - stakater-charts.yaml
  - traefik-charts.yaml
