---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actions-runner-controller-charts.yaml
  - authentik-charts.yaml
  - bitnami-charts.yaml
  - cilium-charts.yaml
  - deliveryhero-charts.yaml
  - descheduler-charts.yaml
  - external-dns-charts.yaml
  - fairwinds-charts.yaml
  - grafana-charts.yaml
  - hajimari-charts.yaml
  - infracloudio-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - kubernetes-sigs-metrics-server-charts.yaml
  - kyverno-charts.yaml
  - metallb-charts.yaml
  - prometheus-community-charts.yaml
  - rook-ceph-charts.yaml
  - runix-charts.yaml
  - stakater-charts.yaml
  - traefik-charts.yaml
  - vector-charts.yaml
