---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: media-recyclarr
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: security-onepassword-connect
  path: ./kubernetes/apps/media/recyclarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-kubernetes
  interval: 30m
  retryInterval: 2m
  timeout: 1m
