---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: media-recyclarr
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/media/recyclarr/app
  sourceRef:
    kind: GitRepository
    name: homelab-kubernetes
  dependsOn:
    - name: security-onepassword-connect
    - name: media-radarr
    - name: media-radarr-4k
    - name: media-sonarr
  prune: true
  wait: true
  interval: 30m
  retryInterval: 2m
  timeout: 1m
