---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"

includes:
  flux: .taskfiles/flux.yaml
  format: .taskfiles/format.yaml
  pre-commit: .taskfiles/pre-commit.yaml

tasks:
  delete-failed-pods:
    desc: Deletes failed pods
    cmds:
      - kubectl delete pods --field-selector status.phase=Failed -A --ignore-not-found=true
