---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-release.yaml
namespace: system
configMapGenerator:
  - name: kopia
    files:
      - repository.config
generatorOptions:
  disableNameSuffixHash: true
