---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-secret
  namespace: dbms
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pgadmin
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: admin-user
        property: email
    - secretKey: PGADMIN_DEFAULT_PASSWORD
      remoteRef:
        key: cloudnative-pg-superuser
        property: POSTGRES_SUPER_PASS
