---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openbooks-config
  namespace: media
spec:
  storageClassName: openbooks-config
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_ATLAS_NFS_SERVER}
    path: "${SECRET_ATLAS_NFS_ROOTDIR}/media/openbooks"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbooks-config
  namespace: media
  labels:
    app.kubernetes.io/name: &name openbooks
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  storageClassName: openbooks-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
