---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openbooks-nfs-pv
  namespace: media
  labels:
    app.kubernetes.io/name: &name openbooks
    app.kubernetes.io/instance: *name
spec:
  storageClassName: openbooks-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: "${SECRET_NFS_ROOTDIR}/media/openbooks"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbooks-pvc
  namespace: media
spec:
  storageClassName: openbooks-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
