---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teslamate
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: teslamate
      version: 7.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  dependsOn:
    - name: postgres
      namespace: dbms

  # See https://github.com/k8s-at-home/charts/blob/master/charts/teslamate/values.yaml
  values:
    image:
      repository: teslamate/teslamate
      tag: 1.27.1
      pullPolicy: IfNotPresent

    env:
      TZ: ${CONFIG_TIMEZONE}
      DISABLE_MQTT: "true"
      DATABASE_HOST: postgres-rw.dbms
      DATABASE_NAME: teslamate
      DATABASE_USER:
        valueFrom:
          secretKeyRef:
            name: teslamate
            key: POSTGRES_USER
      DATABASE_PASS:
        valueFrom:
          secretKeyRef:
            name: teslamate
            key: POSTGRES_PASS
    envFrom:
      - secretRef:
          name: teslamate
    postgresql:
      enabled: false

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-system-internal@kubernetescrd"
        hosts:
          - host: "teslamate.${SECRET_DOMAIN_NAME}"
            paths:
              - path: /
                pathType: Prefix
