---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-teslamate-pvc
  namespace: monitoring
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
