apiVersion: v1
kind: Secret
metadata:
    name: home-assistant
    namespace: home
stringData:
    HASS_SECRET_LATITUDE: ENC[AES256_GCM,data:NdWaNiY=,iv:9tJQI5U+AqxFWR95H0LtmIMq8sABK6ZoaarWG5GhMVE=,tag:I5X0MsEaAy7IeV49pOHg8A==,type:str]
    HASS_SECRET_LONGITUDE: ENC[AES256_GCM,data:chVI5rwdyQ1T,iv:9Uo0AmoEEbaEFQIMGmb2F6nR7kP44S07IbtmnoRJloQ=,tag:JY9xGSHm5x7CKnNSodba/g==,type:str]
    HASS_SECRET_ELEVATION: ENC[AES256_GCM,data:o40+,iv:5H8Q4omU9RIVavhduSxvab10Q47KOooZ6VcwvpSQ3Q8=,tag:j2ECs9N5qAe8YzTuq7sVfw==,type:str]
    HASS_RECORDER_DB_URL: ENC[AES256_GCM,data:+OxoJLnsYdeP/EEdMUTiO0euMB7vlBMkpwe8n39NmmOVmDi8Mc7PISNXt5rpKZz624+WW8KVkudhA14obRXclKW+xqiiHeXXK16Tag==,iv:Qe0QCz9LplNg/7GQouaejfA2UOwspAx0U6u2kZGFbcI=,tag:nD6UPT3PuiFv6TTyS02WJw==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:sNUe5sGLjVtKFlHG9BA0,iv:5YIdQVJAcJ/q0e095wgiLpUWRDRFsrCSdpEfeKV/wuw=,tag:EnatlQUKJxfTvx1d3cnR/A==,type:str]
    TZ: ENC[AES256_GCM,data:D8klYsraIH9efQU2oH96,iv:Dd0E+q7aBfUN8J5BvxQl6CSRkOQBeglemCbm1wPwPrM=,tag:TZIoSR1co0viEbwFAt//HQ==,type:str]
    HASS_BEARER_TOKEN: ENC[AES256_GCM,data:WEzNZP8LaziiNbKvWeoDNme9ykc8RXdrp/8xuMh/5c7BD9zpTSksHK5kacnljNlYmOBgOzOo7I5/G0fLCwIr4tW8mXhdGkwbW4tCmbTf1i1leMmW8ImgybyxEf/ToVZ/AiyN4e7QZ3xWblVn++ZmTYnL3SzHD0Pi5O3rMNbaotLMavVw2JejI38cod0dvD8FkAb+ErU7lz2qA6hDDXkpL4MPxwZoNU9sk/evzITJc8ySBLd+7sKt,iv:aTDLqTdUNwpdkmMz66DMMHdQA6S2vJHwo4NxIC1O6ew=,tag:BEXqx4rlRNeY7+8AdCSRHA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:TyfBB9IjdAKQThqOnIM=,iv:CjoEGTkkGxyyBfjn8UgneTjZd+eaOt95Ci/7I+JL5iM=,tag:8H2GGYWmdW0HxokEHtRICw==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:s9d8A6EAh8OCrYC/ZBo1Eg==,iv:6AxoMKZ/1HJKXECfexr4gUASc4yzMJGLTPcUy2e6Wrc=,tag:mCPA5kcOlO+t8ZYLXVTxPg==,type:str]
    POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:et17zHeate4+ivdeBgcq2A==,iv:yiQsDGxeA6/Pzrv7yJpzjTba9aJAGBwfX66lYu6VFTI=,tag:tMJliWRYXi23PByI1TjuKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPa0dxbno1TWtIeFR1Q25C
            OFllOGY4ZHUyc0x4ZXQ5UjQvc1F4dUMzZ3hJCkg0amhBZS9FN2pVWmVFamJnbTYx
            U0U2dmZIVUpoVGxTNGxzMmU5cUhqZjgKLS0tIEpBR1lPbWV0L3hQbXFxSkdBbDRS
            d2JJc01abDh6aktoeEZqM0ptMzVoOFkKMCiG+UrvP+ns0gQlRrJlzzuLVu2E0XOT
            WRpQytTYp5YU1JKOfEFpsFjCphaGCgKeTywNdVqd4ROMkawtJpHgiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-24T19:55:43Z"
    mac: ENC[AES256_GCM,data:ad68LN77a3V09itf2QNJazY7rzYnGBjYvfcyatkeB7OA2eJqPaddtkXspzQZnECVnvw5CCG0d8bPjSKfqjPe1ypyHfHUWYfto8hZ5t+kY3QP7Tp1mKvTrmp/tGtYw0/MODzEvqAKcWXMxpBn4/a6LD3q78iE0YXxpKnx09KOg7I=,iv:YdA+J2RnWmst+Ckthds+4aYEgKWrVBcC+FB3R+caFDA=,tag:qMuVzRg0G9PiDft+nrQSlQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
