apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home
stringData:
    HASS_SECRET_LATITUDE: ENC[AES256_GCM,data:Fkcw8uE=,iv:u5Kv5ZbavX1yOkOqy3hKaX8GmFGX/HSn5HJH9qCPqN8=,tag:rQ6sknWtxEpCfcvHTvpptA==,type:str]
    HASS_SECRET_LONGITUDE: ENC[AES256_GCM,data:3RWp6fofZwqI,iv:YWaWr20hr2gIZuU9c0Gw72KA2Bm5Xno0c6xdAVuU/iY=,tag:+rrxDFXi7c6rhFpLkfJGYg==,type:str]
    HASS_SECRET_ELEVATION: ENC[AES256_GCM,data:uTiw,iv:7tgbF/TVGjb5uI/bgkmnV2Ecu33bODDt1XyI35SS6iI=,tag:6cm/X4Ry2xphapwZEVzwtw==,type:str]
    HASS_RECORDER_MYSQL: ENC[AES256_GCM,data:bcn040FJIWNIyWJfN2TGoVbyO9Im964BbvtEtLkYnMjEEu4Jlef53iiO9THkvaZNCCqeGS4rWAWuHzfpFuZjKp0hSYd40kVw+WbJR6B7IQ==,iv:UorG1by0cF1N+J0R07x0flnEN7K9X/Hd2z5mH/mP+Js=,tag:3RzR7EGe0XBnIThIXFbJTQ==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:Aemt9lHph7NrL4Bp2dXe,iv:At4HPwu9aKJUJbTf4WfUwkEnWtBHgNTVt3zs0wqvZzc=,tag:hh0wfv23vd/F551/o400TA==,type:str]
    HASS_BEARER_TOKEN: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3d0xmQVJRbWxRTmV1VE45
            VjNHRGFMZE9ZS3dWTjBOQTIvREZvd1IxOXhRCm50SVBHV2c0WnVsTXJKV1hnNEZW
            TnJuYUw2ZFZ2MXpWZmd6bEhzamVtajAKLS0tIEVuVFpqSCtmY0wyWWFYVXV1bitm
            Umx5TDFYMytNWFdwMVI2VXU4WGV3K2sKnnZ1kPKLR6gN0HNqVzqWP+WKrcPx+w4y
            6NLvKTdRdafY02Y76uaNWtABEh1zTuMugjg2XT5GMiHmAG4Bwc95tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-11T09:28:11Z"
    mac: ENC[AES256_GCM,data:M/18gUjfKwUypXmJOA3k/gFXOhFA8vVrt1GmLW7bRV/1eY0rce4oJ5YWvjznnUhmYMkCzm0dEmj1QcNyeb6CR252z5HOJNDvxHbgRUWDkjEoWRCVvb0t1UEENvb0DZj7lqmibSyfSnAgHc/PQuf+jwXzAKvfBPgaoi983jmpZ34=,iv:aYGWL7yRvHFRiyZNB0U1Nin42IpfjYXnt7QPitjhOkU=,tag:cQhhloTJ1mrMrBuCzw33kA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.2
