---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - home-assistant-secrets.sops.yaml
  - home-assistant-code-server-secret.sops.yaml
  - helm-release.yaml
  - podmonitor.yaml
  - rules.yaml
