---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-nfs-pv
  namespace: home
spec:
  storageClassName: home-assistant-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: "${SECRET_NFS_ROOTDIR}/home/home-assistant"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-home-assistant-pvc
  namespace: home
spec:
  storageClassName: home-assistant-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
