---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-datastore
  namespace: home
  labels:
    app.kubernetes.io/name: &name home-assistant
    app.kubernetes.io/instance: *name
spec:
  storageClassName: home-assistant-datastore
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: "${SECRET_NFS_ROOTDIR}/home/home-assistant"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-datastore
  namespace: home
spec:
  storageClassName: home-assistant-datastore
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
