apiVersion: v1
kind: Secret
metadata:
    name: discord-secrets
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:xz+9AS3Axo88E33vsoc/6j+ZRjlxDE5SaTlPyCOSKz+s/S5a1/FIPOtYM5ENS+ZmvdiVKux+uSpZU/AgELZM8xocdZI69xeZ/2XNoBuikzI0zdJC0XbI3atDaECpfxJmsRLPYjdL0R5wjm07rDRZIq7RtiUcq5Hm,iv:RHlu8Hhfu7SfqJo026Oh1cba2CpZ4av5/CEdQBHx7VQ=,tag:qaFhcNxctON5yOvS7B7/Tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bGpBbit6THhWa2xzSWdC
            RzlJeVFyNnV2NVdoSWhTUmlRb0ErUkxBSG1BCkJHaHRteU5laTZqelFmdUNkcExm
            Wk5tcFN5Mkc2WkZrVHhXSytob3RCMk0KLS0tIExkQnpDT3BXTmpxbXZJNmxlKy9a
            TWNTTC8rNDUxQkd2TWVxbkUzbWVxQ3MKGPqEae3fIQvuj7Mv3HxsV//1smfDA+3s
            4UkF+vuDxSQgrEftd/p6CPc0IhKO79RwZ4erByUhXy63ZIACgeWuSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-03T21:00:31Z"
    mac: ENC[AES256_GCM,data:2Ir7Up9A+OOVc0ZMGaVPuHDvhenIXumvO1gLWMUVIFFwxFLSvaJXP0RPuemliJCeRVfFQLyGctFTLUYBT0TLDLQIiIFE6vDYAa+GR4WWwjZyFlbpBp/Lo3s7edDtXbeIeKFtrcocfxSzdhhG0sw+6BgPXNcTv9TX1qwzFJTpCbs=,iv:S77LdvU0ESrwsbQfvwYSpDP57p5UDIuebUPz+OwoQsw=,tag:/OcFS25hEGMwgAJOD2Jd/A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
