---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sabnzbd-secrets
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sabnzbd
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        SABNZBD__API_KEY: "{{ .SABNZBD__API_KEY }}"
        SABNZBD__NZB_KEY: "{{ .SABNZBD__NZB_KEY }}"
  dataFrom:
    - extract:
        key: sabnzbd
