---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - outline-secrets.sops.yaml
  - helm-release.yaml
patchesStrategicMerge:
  - patches/env.yaml
  - patches/postgres.yaml
