apiVersion: v1
kind: Secret
metadata:
    name: outline
    namespace: outline
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Z5WbB+9ydA==,iv:tHBd4y6oxhVlh8tHxyc8bQRCnBdfaiHqS56ltQ7WPQs=,tag:S/3Kx991Ba7/zWZgv7+Gcg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yQd99nqZWK9PWaxIZesxzoITTr+swQ4nlnAXmXkEEqTrcoN9+vmMlMd2cFrKTAPDWFhCv+zn2l1cSEMgW1n2vg==,iv:uYgwzgQFZXPxfbDJFb7EYISXrRbXw+9zjRrXTWIcMls=,tag:bForaWEuDI6EV/KzIQP2LQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:VczuJmYi+CF5DNI5K3qXCMbeS0q1MaR602TQNK4OKx3QKTp5CSSdwWaX+HrOu4Ha5eeJP9su2shQ7E9zOb9V4Q==,iv:8OG8wAGDxR5nf/bVKe+Ofk2KAw6d0pCV/ewVZTl7MGI=,tag:O2rGbEGPpt0zOQyWjF9rGQ==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:weTIvIUJKqSLsp57jM0AZ1Q29e7JqlWKYqnhtRsPUI7zxlyZJlmbQu+tbD9eY0OHv94yRYoJyH0WOgCuQ4MECQ==,iv:V5oYCkEankUabM6vdUKV/e8lJKQlHe3wQfT5r8xzGKo=,tag:oze5DV1ytGeptw8B44o5uA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:MwuOXepUkCUQ1y62xNKFBoj8xAfHoSnHaVVA7QFKbudWWs7smHdvrPmxttdEHibakGSL3Hua7DR8i+lSWrJAEZ0DaB8T+IvzYJ/Umjbl+S2ESC6gv13hc3QLFQF4Hm1QuVegSjIKtIMg9nYDo1k92Uk=,iv:nmO1LCM1h8GxJflkU76wL6pE6fHB5q9MmNK5BnReH/w=,tag:EQv9wZbj2u1/LD5+U0lX2w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:FQEY5jvOUQ==,iv:XkL5Kd5m77ZK7g2fpg8aovdiM2VP23bZhst0vf+P4vk=,tag:hdZKu47KFbmcwkMLQvCg2Q==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:ZHTiVT+wJ8n1omD+VARCqLxmAfXGVkfPTfBqVfR9HtV7OMlSuuqIKVyt4mVBMvO4c2+zVwJcNN8L9g3d0hS9pg==,iv:/Ud9cm7CxL9I0WO3uFvFOkNn9Ngs2M5ThBN79qo7tX8=,tag:jnzfxSotzENOoXcuhsoXPw==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:SunISeR7xPyb34VBy+kfrw==,iv:O9fDCxwQyGJLHOiqe11mUVkdiwz0HliGrBDJRZgX/7Y=,tag:voWf1mMr1bMeD6dAmgtjZA==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:aqRR,iv:Y2c6HE5PUdgz0ILdwuy/pdRxxQ5yfPSeqWM59vKfwmQ=,tag:LUM5OzZWXdrW7j/BjT2zWg==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:J/HKrKGrT8Pfum5pJQaa1pC/jQ==,iv:V/hWM7RiY8JjjxBb13Awp9zIMmJtLdwkq9pH6HwLAOE=,tag:q5i49NcpC3RnzQE7mppqRg==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:aggb1eGo3xQ8/MXVH20yMgXHacn3WAC/,iv:Z7DlBocKcwi/VnjNZZgh5aam+9jdi/bSRwLA9/bRlKM=,tag:7X53gqUChXHIuAl0bILzoQ==,type:str]
    SMTP_FROM_EMAIL: ENC[AES256_GCM,data:Gb28pYW1f4iEQsIl9O3/PB1U5I+5zp8h64kdooHEXaRapg==,iv:kHDPYHav9VZjO/w1E1VBfgiB5zMpG4WDAfI2/s73pGk=,tag:ivH+tqRMEvUSc9XG21+6DA==,type:str]
    SMTP_SECURE: ENC[AES256_GCM,data:sqlaQ0U=,iv:/kv1JH929ENz5dWKT0Qr3EoxZFmD4xZHOKONmqIJL+w=,tag:FFxMJA7cccZkS40xx1vx3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvelpKNHZpWTIrZHQ0Zmd4
            WW5HbmlWcHN6STlDNUNFd0JNY0dBWVBabUMwCjZqbHlMbnE3QzBQWFVMaE4yTlZx
            dTVCZ24rK3hHR1AxaHV2QkVseTZUMHMKLS0tIFRNV053a3B2bnJGVU9ScVdOaXJY
            aTJxOWxDTXI2YVdnUTlYbm5KdGJLNDgKOYM3keLnwb/JCru+02Nqy/GTWigtusWc
            dn4lvBTDc7MUnIKF4Z9zw4ATRm0kJg0sB3kIrWcmzorElHIhErOHTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-29T16:52:41Z"
    mac: ENC[AES256_GCM,data:tNgjPlGd+dsD7YOpEN5lYtgq/po2mB2Gnt9eVrSfaG6oNWbyDZSB7xITKuUJLUjdWVQqpKfKfOsMX9m5yr82v1SHaDNg1EgyH0Qk/3Cmh76LK24xYSaK4E9F8BIl9IeasXRNjDmabdaWy7PQh5QVsELnwHlfD4CnJGp9kLGMKyg=,iv:5Q+58gTYRsr2USNTN0AI4k6fUhXyLKaJyVa+Ayb85Ww=,tag:nAMAGaL3eF0QPg8W/pYwug==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
