---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs-pv
  namespace: dbms
spec:
  storageClassName: minio-nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: "${SECRET_NFS_ROOTDIR}/S3"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbms-minio-nfs-pvc
  namespace: dbms
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minio-nfs
  resources:
    requests:
      storage: 10Gi
