---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-datastore
  namespace: dbms
  labels:
    app.kubernetes.io/name: &name minio
    app.kubernetes.io/instance: *name
spec:
  storageClassName: minio-datastore
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: "${SECRET_NFS_ROOTDIR}/S3"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-datastore
  namespace: dbms
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minio-datastore
  resources:
    requests:
      storage: 10Gi
