---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        adminUser: "{{ .ADMIN_USER }}"
        adminPassword: "{{ .ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: grafana
