---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dbms-cloudnative-pg
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: security-onepassword-connect
  path: ./kubernetes/apps/dbms/cloudnative-pg/cloudnative-pg
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cloudnative-pg
      namespace: dbms
  interval: 30m
  retryInterval: 2m
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dbms-cloudnative-pg-cluster
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: dbms-cloudnative-pg
    - name: security-onepassword-connect
    - name: kyverno
  path: ./kubernetes/apps/dbms/cloudnative-pg/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-kubernetes
  interval: 30m
  retryInterval: 2m
  timeout: 1m
