---
apiVersion: v1
kind: Service
metadata:
  name: hades
  namespace: envoy-system
spec:
  type: ExternalName
  externalName: hades.zinn.ca.
  ports:
    - name: hades
      port: 5000
      protocol: TCP
      targetPort: 5000
