---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: resources
spec:
  background: true
  generateExistingOnPolicyUpdate: true
  rules:
    - name: remove-cpu-limits
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              annotations:
                kyverno.io/ignore: "true"
          - resources:
              namespaces:
                # - "cert-manager"
                # - "dashboard"
                # - "dbms"
                # - "dev"
                # - "envoy-system"
                - "unused-flux-system"
      mutate:
        patchStrategicMerge:
          spec:
            initContainers:
              - (name): "*"
                resources:
                  limits:
                    cpu: null
            containers:
              - (name): "*"
                resources:
                  limits:
                    cpu: null
