---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-superuser
  namespace: dbms
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: postgres-superuser
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
  data:
    - secretKey: username
      remoteRef:
        key: cloudnative-pg-superuser
        property: POSTGRES_SUPER_USER
    - secretKey: password
      remoteRef:
        key: cloudnative-pg-superuser
        property: POSTGRES_SUPER_PASS
    - secretKey: POSTGRES_SUPER_USER
      remoteRef:
        key: cloudnative-pg-superuser
        property: POSTGRES_SUPER_USER
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: cloudnative-pg-superuser
        property: POSTGRES_SUPER_PASS
