apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: security
stringData:
    AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:HVeLkjPQFbV+eWip8RfOdQ==,iv:+CqQMquMR5uBzS7X4Q7SKt85DfJ8UYzsenj6c4TAsMI=,tag:kJ3mQM7kdeV5wzW2W9V0wg==,type:str]
    AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:SYSp,iv:DarVMPXJfzSZUAIqJjNa3eYvEgRsPS2k/HupBqrJdRk=,tag:bcpvFfCEf+mATFwtVT9bfQ==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:EcaCG9A=,iv:Eag9I6XDVYBiefRhKP+itWY05lw9gdr9rSdKZyZ7NDY=,tag:OaegGNazq2zj/SmDwNdodg==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:d918UTZt9BuRsKIs0W6h5YbkrNw=,iv:yYsLyKIJrCO/J3gjX0oaXz4tXHBalB+ffWFRewbeTUs=,tag:Pj9wBrPvC8a/0RmnZmKvCA==,type:str]
    AUTHENTIK_EMAIL__USE_TLS: ENC[AES256_GCM,data:0G91IQ==,iv:GGe69zLJJ4lSpLNK1g0Gwi33/BlNbe+a12SvS5MEwo0=,tag:d7BWPa3gLYyhqOjH0DwwmA==,type:str]
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:wP8b6D933O37DvYEWg==,iv:sKsGJUJr77h29DIBusli5b8SlFcJCFyUv3d+eCp+J7A=,tag:ityyDnDp7NcMWFWj8QQ/3g==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:ovXzJDLmtF/OD+WDr4V0dEYc2tmlPgtrf62FrfYR,iv:Hq7e99pZJuAS95VVbLYfb7sCFZx/R9LqEIVnF6K8Qpg=,tag:A3Q8f6q4AGFUPSQbqRM3UQ==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:3dIV73ikh07mZGlQf8/C9p2sDdhESLYw,iv:9RPR6m32vIiBzRGnEBb9x4M1ELXVE78YD50xAXGcQJ0=,tag:+1G9MJfhtDAkFzIVUpIzzw==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:ng7/v7ZWoXAp,iv:CE+XsYoA12gAzUpATPxdZ5lJAqfJuhLX26T/beqwdtw=,tag:YcCx/7Jyf9V38/B0dVcT3Q==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:jnV2BMGsQu9G,iv:0VGCTvoTySB+6jeTsDhmf2lPBAPoM44wffzA65mI1iQ=,tag:frLtOT538VHR3DuXKXoXvA==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:Oxr3m8pfMcOSItnWE17+WdS+eE36fOj8vbLUiN9y,iv:D9rLex5nJJ7LifVyIkwZoQ9jNnb05Us/pKw5EXKOWJA=,tag:gI9qh//h6gmZ0sPsO/aEDQ==,type:str]
    AUTHENTIK_REDIS__HOST: ENC[AES256_GCM,data:AkvnFNvdgaCbNTB88K+uxfo=,iv:5QLYZXJKE//sNTaJU2zqZL4nOZm+osRvgiyPBar3rfo=,tag:eRfJS26FiMY/QkE2Qlgtqg==,type:str]
    AUTHENTIK_REDIS__CACHE_DB: ENC[AES256_GCM,data:+A==,iv:cS/V4m9qeXFM+QM0Ze71fNUCrQKXclj4qizbHGk8DOE=,tag:6SrqeNtVgewOJv+Krrp6jQ==,type:str]
    AUTHENTIK_REDIS__MESSAGE_QUEUE_DB: ENC[AES256_GCM,data:lA==,iv:XG9OqULtYnWyOzpMHqW4O0ml6VIMRxkD3Uq2gaVstMc=,tag:C7XsY5QZsTs0LuLj2AKJKg==,type:str]
    AUTHENTIK_REDIS__WS_DB: ENC[AES256_GCM,data:lw==,iv:ajovggDB++CdreJ3oy37lO+MtMMr5ccR+IC7dOcNRcY=,tag:VBDwrVcPsfF0GldiEw+D6g==,type:str]
    AUTHENTIK_REDIS__OUTPUT_SESSION_DB: ENC[AES256_GCM,data:QA==,iv:AsAYB6aMdwCFbEmdvaNGYcEKpnqZp3MqR2NWkbNW1ZE=,tag:/5xjZ6VtO+o3EfshJp1jEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhL1dGQTFmOG1ZV0cvZ05T
            RHAvdzVKeFFSMVFEdTJoUVJId2VRM2l5TjFvCjVXaFQ0L1N6QXYrdHFpTzJabk5a
            VHlVMEdRQzBZRjFOazQxOGFXV1dEVGMKLS0tIHZOVUQ3SnloWlZ4U0k4eHVqUXcr
            SGoyb3kwY0hJSjBkKzIxSTB6R1orT2sKZ81PJtApaIkjJoC/RM5+j9SqvkpaoAB+
            FyY3lJNhkxxnptCqR9GQI6Bl+TYz+Bcwvt1yF6FBdNCizkumQxxDEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-27T05:06:05Z"
    mac: ENC[AES256_GCM,data:0SAl67wR2nehO+s45lwS1ac+Ut+e42CZz1hdiTYPGB0f9RHulTxoi2lXUBM3RjXLcT6iC198ECV14FY3j6LF4UhHf1wtKYq8Wg2YiVhiWnVR66Bumm3tYuJ+5B94D01aM0UdNuy1r9JThKf/FIehOC8oLbpUH0yeh3YmMIuhiO0=,iv:6YYUatUQ6kuvwYFqG8JmmRdxioPxMccYMy1Ae/awsKw=,tag:K5aFcsDURV8vu+xSSr629g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.2
