apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: security
stringData:
    AUTHELIA_TOTP_ISSUER: ENC[AES256_GCM,data:3Ut2VY/sqQ==,iv:K1TzzBt7G7u/IpgXdLQf37IfiEnfrV9Y9iKtDDKvERU=,tag:RQv+tPCvFpXbM7w4L75/4A==,type:str]
    AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:gAehx3LEOcl8QF9Vb6iRIi6wS5IqUq73UxCXMqd5BAwkfiwP1U0MvxUotYmaRt3TRBy3WPlXZoHUiH9PRxFZVA==,iv:UBTsE/3C1tM4S6W/+izJjO6PD2klXeOG753aaylRwTU=,tag:CJrml9bjOsZ0IO4sEKUoGQ==,type:str]
    AUTHELIA_WEBAUTHN_DISPLAY_NAME: ENC[AES256_GCM,data:wGMrVeR+a1gJfdZ6Ag==,iv:uueYeRVb0w35OxiFwuNI4nYeWRtTDcOCZ4F5Tf/inyw=,tag:tGGd/A85c28D+I1jSIKp0A==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:fKuRyZ8Wnsy6yRyLOeq/snUHG8ruPwV8eU2NyGHmZLHTde98dOJqdhYOD1OAJrfNfUYNYnWntpD88xIgdb4sqw==,iv:oGBegiWfjfbkSVM/xNTRhX5bs9mmz1pDY5rgvNLyjio=,tag:JC0wkxbOQOD3+nh1ls6XHA==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:B1gcZvZBca92z+urt3KwY3EDJ9h9EYYlIM1XztWjeDU3mtPvNh9zt1Jj2C3SSJywLU4cS9t9dV6BgIGUiGK03g==,iv:cFXUIK6OzYA7Gdh3AhrdOHgnjJQ1DaAyucNZG+gjXAY=,tag:qkKFT/4/DhiZWcTFQhzn1A==,type:str]
    AUTHELIA_STORAGE_POSTGRES_HOST: ENC[AES256_GCM,data:rndq4tIPHtXMPvXhli5/0w==,iv:Q6aZEMHAPiZUsfweZaTvdFRweE8q3GpBWPVkh1vUa3g=,tag:b51N1HLtzEPA9WJ1oAJ7FQ==,type:str]
    AUTHELIA_STORAGE_POSTGRES_DATABASE: ENC[AES256_GCM,data:gQ5jX9KqxqDcio4GyQ==,iv:fNG7bdlennf/xogBUDLQoi5SurYbKTvP/5Lhkt12zDQ=,tag:q61mAN+f89AHtJXG95blDQ==,type:str]
    AUTHELIA_STORAGE_POSTGRES_USERNAME: ENC[AES256_GCM,data:wV/8GK3bqmjmAB8i+w==,iv:a7qHT2IfGRWPROdWhW2QtiJgjrkRpjxwf4jsJ/7xiBY=,tag:5yFEsQo4e02y6wmqOWwBGQ==,type:str]
    AUTHELIA_STORAGE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:rLWfvNhFipdcAusJWDIL4pVZs/8nFGJYWDPZmRb5MQ==,iv:FCoZdJ+NeVKBNtAnN2R6feoU82Aw2CUWI2O2nYA2NP4=,tag:wIoxzsufTswqp6ffCvhH7w==,type:str]
    AUTHELIA_NOTIFIER_SMTP_HOST: ENC[AES256_GCM,data:zPlexbqVFBWJhBC/KtXLHQ==,iv:patnVmXZSEsOSz6cwdRcr37DqO7i/WxB11+Movb5XEo=,tag:e+7gAEs5h7sNXYUX1GfqaA==,type:str]
    AUTHELIA_NOTIFIER_SMTP_PORT: ENC[AES256_GCM,data:FTAo,iv:eMqKBpnyp/xzUpHRmiJFTDTgsJ5C8pVlCphtkB8lz/o=,tag:cpmm1fAVAifBKcT23IZYIQ==,type:str]
    AUTHELIA_NOTIFIER_SMTP_SENDER: ENC[AES256_GCM,data:NKFXEJQubahS+8zpUPXVqJyJucKt9J60jqmJhuSxyhropYgiGg==,iv:AhJ4RJSpzh5bCf8uyWWUh1SaQgBCIZAzBQ3yP/g1zXo=,tag:HmkMvUz2tqWD10CuVevUxA==,type:str]
    AUTHELIA_NOTIFIER_SMTP_USERNAME: ENC[AES256_GCM,data:B5eskpCRNnpu99O7W0hGuyDmNl0=,iv:5ytxwVDbmwuCm6Aj5G+KPRx8Z6I6WmJTztFyMXExENw=,tag:kY8sA/Xz0+rCW0F5vKJG+Q==,type:str]
    AUTHELIA_NOTIFIER_SMTP_PASSWORD: ENC[AES256_GCM,data:Lv+hE8hiyQ2dc/QjB0KfSZ5JX1s=,iv:jhqOafemPG8dqR6YKXybfG1JCT1Dv2wt+DyMNavhKAE=,tag:CnA/w5XAXzVvCxvaHS3Neg==,type:str]
    AUTHELIA_NOTIFIER_SMTP_STARTUP_CHECK_ADDRESS: ENC[AES256_GCM,data:B+veFmCmn+kNyk3baeA=,iv:4hWrHcvehMTkQItSgjq5bw/VQrGXq+MORhXW4CtvPdk=,tag:qUMkNozrqTVHS0b2PjgHnQ==,type:str]
    AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET: ENC[AES256_GCM,data:oHdze+Z9LhGpdESRu+i/0J3VUDJRwmPYuyaqckRIb9GC4pPkYkSnI+sUQhuZgD4Rrlz8gYpq9jsmuGSkfnG0eA==,iv:wcph1eY7ULmNJ1tO7Lif3UunpbmwPoBjlz2H6oRxqCU=,tag:5ESv6P8tOrC0Hye5L46IWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQlhKUnN0bzdEN2w1Nndp
            N0RVMk10TlkzazhrS2ZiTTJtZVJkcHA2R2owCk5OcFI3Y1p3MnhrUzRkd3NnWjNY
            amQyZVpEcEpBT2kyQlJLcmh2RlNjWkUKLS0tIG1PUWlDeFBUNldnQjVpY2pRdzI4
            ZjZveVRuczdOcEpJTjkrY0ZGK3VpS1UKseI+ZW7POkv+eorITkPD1glyotjDsQIA
            alElA0vl8YDrPeDw7rYGs/YuhbH3im6+5cQJnw+H/muxSVAznKApZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-29T17:03:18Z"
    mac: ENC[AES256_GCM,data:280ktRWmJRmoL5NUqnt3Vas8qSswDPGY04alJLlSY2AIOmieg/wyV/SfnCyVW7CIJ8GDa2o7kUltdsLJKfsmLkPkAQFC6Jytei+mLfKM7kxor+VZJbuzmVubBRbZq8ixHwgz4XmjPTSH2bs1yDCxZ5tvPKJ4GX6KjLK5hCKzLfk=,iv:izJHxI8iU/QZWL+g0S0gWSJOaPg7y9wjubrYwsIAZpI=,tag:U4YOkq6wIcTXQ5VQXgBz8A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
