---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: web-tools-outline
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  dependsOn:
    - name: dbms-cloudnative-pg
    - name: security-onepassword-connect
  path: ./kubernetes/apps/web-tools/outline/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: outline
      namespace: web-tools
  interval: 30m
  retryInterval: 2m
  timeout: 1m
