---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: shlink-api
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/web-tools/shlink/shlink-api
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: shlink-api
      namespace: web-tools
  interval: 30m
  retryInterval: 2m
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: shlink-web
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/web-tools/shlink/shlink-web
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: shlink-web
      namespace: web-tools
  interval: 30m
  retryInterval: 2m
  timeout: 1m
