---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediawiki-nfs-pv
  namespace: home
  labels:
    app.kubernetes.io/name: &name mediawiki
    app.kubernetes.io/instance: *name
spec:
  storageClassName: mediawiki-nfs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: "${SECRET_NFS_ROOTDIR}/home/wiki"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-mediawiki-pvc
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mediawiki-nfs
  resources:
    requests:
      storage: 10Gi
