---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: dbms
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: 17.0.11
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      registry: public.ecr.aws
      repository: bitnami/redis
    auth:
      enabled: false
    master:
      service:
        type: LoadBalancer
        annotations:
          metallb.universe.tf/loadBalancerIPs: ${CONFIG_SVC_REDIS_ADDR}
      resources:
        requests:
          cpu: 10m
          memory: 32M
        limits:
          memory: 34M
    replica:
      resources:
        requests:
          cpu: 10m
          memory: 32M
        limits:
          memory: 32M
    metrics:
      enabled: true
      image:
        registry: public.ecr.aws
        repository: bitnami/redis-exporter
      serviceMonitor:
        enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 32M
        limits:
          memory: 34M
