---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recyclarr-secrets
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: recyclarr
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
  data:
    - secretKey: RADARR_APIKEY
      remoteRef:
        key: radarr
        property: RADARR__API_KEY
    - secretKey: RADARR_4K_APIKEY
      remoteRef:
        key: radarr-4k
        property: RADARR__API_KEY
    - secretKey: SONARR_APIKEY
      remoteRef:
        key: sonarr
        property: SONARR__API_KEY
