---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: dbms
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 50Gi
    storageClass: ceph-block
  superuserSecret:
    name: postgres-superuser
  monitoring:
    enablePodMonitor: true
