apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser
    namespace: dbms
stringData:
    username: ENC[AES256_GCM,data:NyYFvq7D7N8=,iv:vdaJ5+lDsATUSz+PfW9GQY4oA0Dc1TA5pmKO7ZUEywQ=,tag:sORGe7kr2aw3bfw+sGd+Dg==,type:str]
    password: ENC[AES256_GCM,data:QLimkEE5WP4339KWtVankA==,iv:LXpDNKsn7fayOtoxiCuJbQbtcrgMJua9Si1rMz0LkHw=,tag:DJrQdsswiP+mqLkwCq1cqg==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:UjAyw2O0VuwAew==,iv:vLqYE9Ar9+QkLdRpHZD0IhgJKzViS/qUSPYPgDWCYn0=,tag:iF9QCeCT1MQWKSP5AVH7Hw==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:j45NEfE0guYlW1BzJbz425hZJFCY+ztRQQVCs/1YbYTHqlZ3NnMy85o2F1JS+r/el61ISCRbnHgWdH8fP+kHLw==,iv:GNopLqCl2LxEDPQ/3KhipLplY6Wnf/FGbmKGiZ5MLQg=,tag:EDSBY2xAzv9X93jerLn1YQ==,type:str]
    MINIO_REGION: ENC[AES256_GCM,data:CWSXcf5Mm7M=,iv:Bs6Kk/ACxsHVXZrU78tj84P56MwQajrEc8hm0lQeNRw=,tag:Bnaxzw2bsbiYk4UQNMNjhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaM3ZsUFVJVHlqNXFadWJy
            Z0lHYkZjZmp0RmRCeDl5enFMdWhqMnhkSlFVClRuY3A2ZGxUTVd4d3lXdCtlUjRL
            U1RuNG1RRnlHVFdhY0dlejJwVC9VREkKLS0tIGJLclBYMVNYdHNQR2x1anZCNy9W
            eldTT1dHQ3hpNnVaWmhCYXMyZWVhVDAKz1pOOpW9O2W2kGb4V19bC1K99ewgGzol
            Bm/iavf1BeDguFeutKSa97bZpSuMpQETPPlDAy+aSOq1zD6zdWdEHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-23T10:27:04Z"
    mac: ENC[AES256_GCM,data:s4caA14udM+CEYN/S6dBopw+Sds4cnvxhEUTTv9LrzwL3b3bNLNH4EO3tdmBe1xdk5yR147p6ue23EWV461t6z2kCKVpQkZWIfXVvELxHZsB5hErBGSZ0svRpGg2Nzn+0RWen/qWZ9gd4nq5OnddcNvFbbTrpHz9Mw7CrBvyD3o=,iv:S/PASSlWrJ6zf3VRAIRgQw8l/n98HBQ+5PRzaBjEdpg=,tag:qe2g1uKsfZFYO8pPHxWr0Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
