---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-shell
spec:
  terminationGracePeriodSeconds: 5
  containers:
    - name: shell
      image: ubuntu
      tty: true
      stdin: true
      securityContext:
        privileged: true
