---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-secrets
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: external-dns
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        api-key: "{{ .API_KEY }}"
        email: "{{ .ADMIN_EMAIL }}"
  dataFrom:
    - extract:
        key: admin-user
    - extract:
        key: cloudflare
