---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-secrets
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: external-dns
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
  data:
    - secretKey: api-key
      remoteRef:
        key: cloudflare-secrets
        property: API_KEY
    - secretKey: email
      remoteRef:
        key: admin-user
        property: email
