---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app readarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        secret.reloader.stakater.com/reload: *app
    image:
      repository: ghcr.io/onedr0p/readarr-develop
      tag: 0.1.1.1320@sha256:e859dc1e2a77ee936f974b77f92a4f5b7e242d0b890d4cee57cfa18dacc2590e
    env:
      TZ: ${CONFIG_TIMEZONE}
      READARR__LOG_LEVEL: info
    # envFrom:
    #   - secretRef:
    #       name: *app
    service:
      main:
        ports:
          http:
            port: 8787
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-system-internal@kubernetescrd"
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN_NAME}"
            paths:
              - path: /
                pathType: Prefix
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          exec:
            command:
              - /usr/bin/env
              - bash
              - -c
              - curl --fail localhost:7878/api/v3/system/status?apiKey=`IFS=\> && while
                read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
          failureThreshold: 5
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: readarr-config
      media:
        enabled: true
        existingClaim: media-datastore
      downloads:
        enabled: true
        existingClaim: downloads
        mountMath: "/downloads"
      backup:
        enabled: true
        existingClaim: media-backups
        subPath: readarr
        mountPath: /backups
        readOnly: false
