apiVersion: v1
kind: Secret
metadata:
    name: radarr-secrets
    namespace: media
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:tfvQZllFsngznXZVpmgwnUhte76ilG9cwsgNbpT1D9U=,iv:GrvhBUiJtEQdbmUS0Ve1weLP5r1WLYxdxZYHEJQByWM=,tag:nerWKm8wAFRxfDoYXdLqlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dzF5SjNQZWVuRFVyWGJB
            cHQ1QUJ3bGtGWFBJUytNTkcvS0hDY0pTRENJCnRuKzFQVTZkajVlb29pQytWMTFI
            NDQ5RnN1VWlVZDJ1dGJiV1czRWQ5d1EKLS0tIFEwQW9NeG1LOFdNTVJNeXNCd01S
            TVBMN3RLbUZJMkYvV0dRV05KaEhlVHcKjzBCDbPrGF0SBRanCYbHqWgjlMTrFlTE
            /tDGGOcOefQuy+x+b4qMfTPCCs8Bex+gYxQMx6XVkFKI90VZE0hQGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-13T01:25:22Z"
    mac: ENC[AES256_GCM,data:5uc8nV67Cs9jWEGwVZfEz5nCO+2y1SJ4UScyxvx3kWE8/3TfPQFQqvFC+dzmHqeT18sl+HvKZcZBRjiDErzCQ8LioQj/vJrpXSAO692UFd31vtn0QlOW3qibSmZU1hSGHFVJnPTuS9Q0ZHv530EsazEH4NVgQY5WZntvyGy+G0A=,iv:sazDULJxcs3HMx906G1RRUIRqpw6n7toALCQHLtjrJ0=,tag:wupppVpiaSp7ZU/1rT5ffA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
