---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    prometheus-operator-validated: 'true'
  name: radarr
  namespace: media
spec:
  groups:
    - name: radarr
      rules:
        - alert: RadarrExportarrAbsent
          annotations:
            description: >-
              Radarr Exportarr has disappeared from Prometheus service discovery.
            summary: Radarr exportarr is down.
          expr: |
            absent(up{job=~".*radarr.*"} == 1)
          for: 5m
          labels:
            severity: critical
        - alert: RadarrDown
          annotations:
            description: Radarr service is down.
            summary: Radarr is down.
          expr: |
            radarr_system_status{job=~".*radarr.*"} == 0
          for: 5m
          labels:
            severity: critical
