---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: resources
spec:
  rules:
    - name: remove-cpu-limits
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              annotations:
                kyverno.io/ignore: "true"
          - resources:
              namespaces:
                - "flux-system"
                - "cert-manager"
      mutate:
        patchStrategicMerge:
          spec:
            initContainers:
              - (name): "*"
                resources:
                  limits:
                    cpu: null
            containers:
              - (name): "*"
                resources:
                  limits:
                    cpu: null
