---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: ghcr.io/onedr0p/prowlarr-nightly
      tag: 0.4.5.1955
    env:
      TZ: ${CONFIG_TIMEZONE}
      PROWLARR__INSTANCE_NAME: Prowlarr
      PROWLARR__PORT: &port 9696
      PROWLARR__BRANCH: nightly
      PROWLARR__LOG_LEVEL: info
    envFrom:
      - secretRef:
          name: prowlarr-secrets
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-system-internal@kubernetescrd"
        hosts:
          - host: "prowlarr.${SECRET_DOMAIN_NAME}"
            paths:
              - path: /
                pathType: Prefix
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config
      backup:
        enabled: true
        existingClaim: media-backups
        subPath: prowlarr
        mountPath: /backups
        readOnly: false
    prometheus:
      podMonitor:
        enabled: true
        interval: 10m
        scrapeTimeout: 2m
