---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: prowlarr
      version: 4.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: ghcr.io/k8s-at-home/prowlarr
      tag: v0.4.0.1793
    env:
      TZ: ${CONFIG_TIMEZONE}
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "traefik-system-internal@kubernetescrd"
        hosts:
          - host: &host "prowlarr.${SECRET_DOMAIN_NAME}"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        existingClaim: media-pvc
        subPath: prowlarr
      backup:
        enabled: true
        existingClaim: media-backups-pvc
        mountPath: /config/Backups
        readOnly: false
    podSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    prometheus:
      podMonitor:
        enabled: true
        interval: 10m
        scrapeTimeout: 2m
