---
apiVersion: v1
kind: Service
metadata:
  name: octo
  namespace: envoy-system
spec:
  type: ExternalName
  externalName: octo.${SECRET_DOMAIN_NAME}.
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
