---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discord-secrets
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: discord-secrets
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
  dataFrom:
    - extract:
        key: flux-notifications-discord-main
