---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discord-secrets
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: discord-secrets
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        address: "{{ .DISCORD_K8S_MAIN_WEBHOOK }}"
  dataFrom:
    - extract:
        key: discord
