---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-minio
  namespace: dbms
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: postgres-minio
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        MINIO_ACCESS_KEY: "{{ .MINIO_ACCESS_KEY }}"
        MINIO_SECRET_KEY: "{{ .MINIO_SECRET_KEY }}"
        MINIO_REGION: "{{ .MINIO_REGION }}"
  dataFrom:
    - extract:
        key: postgres-minio
