apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secrets
    namespace: media
stringData:
    SONARR__API_KEY: ENC[AES256_GCM,data:71nQXMX7GC4A0I0UPV9ACiO4uO9r7eegHIlrHflvKqs=,iv:FaBv6KsNq60s4yM70JSVeDTzcLXmjnBHW2NNx7OySTc=,tag:eHWPRyI+H9Qs4dEmrCbwNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXankxNkl5Wk9pVXlSMDBp
            YkhHdHpwN1pRNlZnOXNHWnlEVTEvNTI0alRzCmVZQXlTNmNjLzcyOXJIN0VlcDBO
            S1lJTGdvQ3czUDJjZGx0emxnZU04K2sKLS0tIHFPOFRhbHFsemxwSk1odmRkczdy
            dkVid1F3NGM4U215aDQ5OE54M0ZnTEUKFHF7Pqt5pkvF9fcd4RFjisqDR5VOlTgb
            DyL8DdtKfyiZqY+ld1duQjkhK9SxY8fJbgWOYUhJz1qDCfT1hB0byQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-13T01:25:22Z"
    mac: ENC[AES256_GCM,data:OJxndKbx1nYWaAp9Bzu8uDue/z/XiCErf3qrnFHBXAXbqjeITimK8uELS2P27hTbs+KE77pOsDAGQScE80fmKgiiaKI3PHNDUOWadvOygXEs9GjSGkqmdfsiVGDR0liLLmN6WvY3lz1Gl15zX+4/ByiSYWTucfK6+cLjMOiDMsk=,iv:iMy2YJUSd0RvTl1ZTn1lnQu36CaXBfykXCfgD/LyAqc=,tag:JmHAgpPYZbh0BpNBosOOkg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
