apiVersion: v1
kind: Secret
metadata:
    name: unifi-poller-secrets
    namespace: monitoring
stringData:
    user: ENC[AES256_GCM,data:Eg1l+xgOBBjF1+c=,iv:wc/Gxgr4TaM7/upMTI6OxTuBeAtNQh24VtRnXudhJkk=,tag:rj+i1Xd0SphRsuV5+3cJ/w==,type:str]
    password: ENC[AES256_GCM,data:1R+FKWM2bgA6cvKgjA==,iv:eKDMoRuzU/rv4mx11KM3RFX9ai9PhoHXEI/bl+iJ8yc=,tag:ocuLE6IFj+pcVcJIz0QNHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVV2Zjek9OTEJ3clcwOGVt
            Q1pJd0hCclJIL09zVUpiQlZtc2JUQTVRQ2w0CittcThrWWV3TUk0Mk1ybEhFNHJq
            MDVUMDF0M2FiaXdjLzV6MnJUaGwrL2cKLS0tIG4zeGZROVNFMVVWQ09aZE1ESEcz
            dVZhaHNkMWRYS3NDY0JYSjFXb3hpWmMK5a2BZSdtyiYgoTpE36WF9cwum8wN7Xee
            +WAp8cQTHX4x/FxUstn4DA/i2N/kZKr70p4pvJ1eAGaGeVJrE+7ppQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-08T03:34:20Z"
    mac: ENC[AES256_GCM,data:jVAgtId08a7ffljQ6d6Re6Cb6xXlE0aOIJ5vklvYXyaupMzisW/LqbVwYAJ3G3lI04jGtA2doiZHjRGw4hgNiyFgA7CBke+XDD4E4a4ZIuqvFcEbqyKPz1j4hLtPMHHOREC9VjIpBqVqfkMfT0JEps9I0KhCT8UD7qDQ1/Fl+9A=,iv:7/6slHsD27RhjPrs6bZb4QlkGt7gPresZm0RdAn0e7c=,tag:OOmRhTvg/Dnnvl7ylWoIGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
