---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: &app radarr-exporter
  namespace: media
  labels: &labels
    app.kubernetes.io/instance: *app
    app.kubernetes.io/name: *app
spec:
  selector:
    matchLabels:
      <<: *labels
  endpoints:
    - port: http
      interval: 3m
      scrapeTimeout: 1m
      path: /metrics
