---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-code-server-secrets
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-code-server
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        id_rsa: "{{ .ADMIN_SSH_PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: admin-user
