---
clusterName: ${CONFIG_CLUSTER_NAME}
talosVersion: v1.2.2
kubernetesVersion: v1.24.5
endpoint: https://${CONFIG_CLUSTER_NAME}.${SECRET_BASE_DOMAIN_NAME}:6443
domain: cluster.local
clusterPodNets:
  - ${CONFIG_K8S_POD_CIDR}
clusterSvcNets:
  - ${CONFIG_K8S_SERVICE_CIDR}
cniConfig:
  name: none
nodes:
  - hostname: k8s-1
    ipAddress: 10.0.40.16
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
        vip:
          ip: ${CONFIG_VIP_IP}
  - hostname: k8s-2
    ipAddress: 10.0.40.17
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
        vip:
          ip: ${CONFIG_VIP_IP}
  - hostname: k8s-3
    ipAddress: 10.0.40.18
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
        vip:
          ip: ${CONFIG_VIP_IP}
  - hostname: k8s-4
    ipAddress: 10.0.40.19
    controlPlane: false
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
  - hostname: k8s-5
    ipAddress: 10.0.40.68
    controlPlane: false
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
  - hostname: k8s-6
    ipAddress: 10.0.40.21
    controlPlane: false
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
controlPlane:
  configPatches:
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
        rotate-server-certificates: "true"
    - op: add
      path: /machine/install/extraKernelArgs
      value:
        - talos.logging.kernel=udp://${CONFIG_SVC_VECTOR_AGGREGATOR_ADDR}:6001/
    - op: add
      path: /cluster/proxy
      value:
        disabled: true
    - op: add
      path: /cluster/controllerManager/extraArgs
      value:
        bind-address: 0.0.0.0
    - op: add
      path: /cluster/scheduler/extraArgs
      value:
        bind-address: 0.0.0.0
    - op: remove
      path: /cluster/apiServer/admissionControl
  inlinePatch:
    machine:
      logging:
        destinations:
          - endpoint: udp://${CONFIG_SVC_VECTOR_AGGREGATOR_ADDR}:6002/
            format: json_lines
      network:
        extraHostEntries:
          - aliases:
              - ${CONFIG_CLUSTER_NAME}.${SECRET_BASE_DOMAIN_NAME}
            ip: ${CONFIG_VIP_IP}
      time:
        disabled: false
        servers:
          - ca.pool.ntp.org
worker:
  configPatches:
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
        rotate-server-certificates: "true"
    - op: add
      path: /machine/install/extraKernelArgs
      value:
        - talos.logging.kernel=udp://${CONFIG_SVC_VECTOR_AGGREGATOR_ADDR}:6001/
  inlinePatch:
    machine:
      logging:
        destinations:
          - endpoint: udp://${CONFIG_SVC_VECTOR_AGGREGATOR_ADDR}:6002/
            format: json_lines
      network:
        extraHostEntries:
          - aliases:
              - ${CONFIG_CLUSTER_NAME}.${SECRET_BASE_DOMAIN_NAME}
            ip: ${CONFIG_VIP_IP}
      time:
        disabled: false
        servers:
          - ca.pool.ntp.org
