---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openbooks-config
  namespace: media
  labels:
    app.kubernetes.io/name: &name openbooks
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
