---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboard
  - dbms
  - dev
  - flux-system
  - kopia
  - kube-system
  - home
  - media
  - monitoring
  - networking
  - security
  - web-tools
  # - whoami
