---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - dashboard
  # - dbms
  # - dev
  # - envoy-system
  # - flux-system
  # - kube-system
  # - home
  # - media
  # - monitoring
  # - security
  - whoami
