---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: media-lidarr
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/media/lidarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: lidarr
      namespace: media
  interval: 30m
  retryInterval: 2m
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: media-lidarr-observability
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/media/lidarr/observability
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: lidarr-exporter
      namespace: media
  interval: 30m
  retryInterval: 2m
  timeout: 1m
