---
apiVersion: v1
kind: Service
metadata:
  name: pluto
  namespace: envoy-system
spec:
  type: ExternalName
  externalName: pluto.${SECRET_DOMAIN_NAME}.
  ports:
    - name: pluto
      port: 5000
      protocol: TCP
      targetPort: 5000
