---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex-secrets
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: plex
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        PLEX_CLAIM: "{{ .PLEX_CLAIM }}"
  dataFrom:
    - extract:
        key: plex
