apiVersion: v1
kind: Secret
metadata:
    name: plex
    namespace: media
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:RYEdyVJqx/tbk+uhqdzaNvCpXDmgb83ezX4=,iv:iQFS1LCM9YGKKjK4O0gt+8Og6aDBJ3iuhxIodujSIdc=,tag:BItDKbq4pv8zgGGsBg5D+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RThYeHU0U2VZZHpkKytT
            NFBiU0FkWUFvWnZoUStFUGxpNHBGTmdvdWpJCjZKV1ZvVnBNb09kRWwwWmlZQVlr
            amRkSUdyUm1CQVY5bm9KSVpzbXJvZW8KLS0tIFZHWnBuZXNtZ0ZRR1dneE03d0dZ
            WlQxY1NmQU1LRUFqbUp3dS9uMFM5N2sK0ZVvjZ7izgvptoWkUdemv07suP+4ICeM
            ulqSNKwLMjzHP+z3Wp2fidfiY6SF2VhEqwHsRzQLOhH5nGTlXbv4Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-20T00:17:27Z"
    mac: ENC[AES256_GCM,data:q6/k/tWGX+nQdBJDLEzvQ5xuE4quc4xQI6+SgE7Jlz1BVmgJU41xSLMM6WEfCSRNFdNTuYDAj2mq7lP2JZJSinBozXXQpcTdv7E/CWoota5LKJgQs634lwWepmf8fW3Q5ckjJfWmxYCUqJ/WqNokFGnBv4qcrrBJwi/h3yOu1kE=,iv:ZLlaTAjrGEzYLhUCOe6rnEIcbNQvVONGvjI3qr6dVhg=,tag:Z1Q18wCCKSBmrosNphfvzg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
