apiVersion: v1
kind: Secret
metadata:
    name: lidarr-exporter
    namespace: media
stringData:
    APIKEY: ENC[AES256_GCM,data:MBKIQvOHTC997kfSOOTp1RBwPS3cWmPh4jvChqZvNYo=,iv:O03962vH+C8u3h75m2PYrTW3t2TcHw3SRKOPDiaH4r0=,tag:xwU3QU9ZCWpFnmezop/0Og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUHRpSU03WSszNHppSWRn
            REJnZndHQWczSGtsU3hkNFd6cUFrZDY0STE0CjYvMEh2QWdQVy8xeTRIc1hOSlk2
            SERIc2M2RmFYaUZsMzVrR2hSU0tGKzQKLS0tIEVmUW1pTi9oUXRWcUlaRGIyZVpK
            Z1lYY0VtdUh5VFE0L1V6SEo2VFBhR0EKdT3Fhsk/b/+P0/K9KSux4T0aCo2VzLaT
            h2KKFMSXWZAbTQRqpKOg3YV2+KqkjpXR7oD2qi7K6EyO227XqZo4rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-05-22T12:32:01Z"
    mac: ENC[AES256_GCM,data:DySUW++Sk7aVHfWO4vPC0N+vNaCwQudCxdaYmAwkzeGIehgInlGIOdey+KYbe/MsFtJaPLAyhSR8eTZ4e5YUGcPSlhHL3yfI9/8GqIVaBqY2BXi7CGH+fzmHaDMkxoo2FDS0E2onP7x2CFr1zJBVSbHAXxu8rNjNjZfQDmtaBZk=,iv:uFkyNfO/m0leG3piSY5ORiwjNM/abjTYOVp967ioNHE=,tag:eiHGGkmsMGR8DXLFn7EdfA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
