---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: networking-cf-ddns
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/networking/cf-ddns/app
  sourceRef:
    kind: GitRepository
    name: homelab-kubernetes
  dependsOn:
    - name: security-onepassword-connect
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cf-ddns
      namespace: networking
  prune: true
  wait: true
  interval: 30m
  retryInterval: 2m
  timeout: 1m
