---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actions-runner-controller-cache
  namespace: dev
  labels:
    excluded_from_alerts: 'true'
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
