---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actions-runner-controller-cache
  namespace: dev
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
