---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - teslamate-secrets.sops.yaml
  - helm-release.yaml
  - teslamate-datasource.yaml
  - dashboard
patchesStrategicMerge:
  - patches/postgres.yaml
