---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teslamate-secrets
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: teslamate
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
  dataFrom:
    - extract:
        key: teslamate
