apiVersion: v1
kind: Secret
metadata:
    name: teslamate
    namespace: monitoring
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:NlXIJAG+VA+mXdw6tpqRxYTkIafbFaxG10bmWoQzArYsSjq9x6xdaOSK6VB0uhkKVWg7xiiDwznb,iv:i8PbL2pKrM0K3Fh9X97NMjvPvnOZvKjsLDnAwfAU0IY=,tag:Pf8Px+er/WRiyPUYqkAm7g==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:8Jmgx/S7Pad3,iv:DgaYV5RXic0nn9eLM5PS/G341L+EAihtaj0K/4o6q2s=,tag:m8ZfHirhi2AePkcnce7ozg==,type:str]
    POSTGRES_USER_FLAGS: ENC[AES256_GCM,data:DAA=,iv:gUdLidRhHXZ01B6phU4sX0tDeP4vLILHCGun1wCEfPU=,tag:c7yeKoWfeioCCAVEdRCC0Q==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:WU9Z0edcAoGmG0pLNNJaXQtiVxCbo7Vb,iv:Bd77nGTa0SMNZbQXDriTWns7sk8X4xrsEufMGSJA748=,tag:rXw4a9L2DViU3bGBECDWqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQkRsSnJ5NU9UME4xU3h5
            WXNZVzFTSmQxckZmY1c3OXlVenBKOWo1elI4ClI0RDhzZzA3Y3VZOWxWVFlpZnBL
            YzE3NU9FVWQwUTBpdlNMVlMrSGxxYWMKLS0tIFJ5b1ZqNG8vc1c1SG1vTGhYTXdX
            bjNiV01Rb1Zkckw1bG1oY3B6UlRieHMKahKczL1rtUaIixqCf/Tlj8FtYO5TuXRU
            s/Ikl70uBQInUtEowJ8mhYOYo+8912j2BN8cn8VHzOdiKmEiL7aPzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-29T16:54:50Z"
    mac: ENC[AES256_GCM,data:LSuHYrxq4eg5OZ0PS0sDL3j6lzoX3uN61f8pxjtj5qKr0mzhEwyUYCmdM6JZI4wJTwjlUwSvHvDEI198vQHvjXSq0n0i7J0Fzx09WLCFWyTZBFc4mNk06mi6/WS1IHbrCjH1CY7WSQVCyGS25W/tj5OEEmvgbqepzK2PVFtj/JU=,iv:E9OO+9W+ABU2scnPOzTmwX1DBp/8oJTcX1WgERq3vJo=,tag:L3O+htQYmo6CRALXVutXMw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
