apiVersion: v1
kind: Secret
metadata:
    name: authelia
    namespace: security
stringData:
    AUTHELIA_TOTP_ISSUER: ENC[AES256_GCM,data:owXzbw8TOQ==,iv:FnI8aCejtWvzdX2+VIfIYn+8HKLkicaphTX5xejjXJM=,tag:RJKeZ2bQxVV3EK19PYGgeA==,type:str]
    AUTHELIA_JWT_SECRET: ENC[AES256_GCM,data:KnllMrX50oS9PERaIy+S2J2g1piWPgC9IV0WRzFTin9GQyeOLxztXYPhMaWSQfgzbXTP94qKNiTWGM4ZCOk+9A==,iv:DBm+4+DFnyC8aIEQBQkm0VjZverd3+LErMQz2Sz0KDE=,tag:5VqukDmqQd4/6YIYHkNC6g==,type:str]
    AUTHELIA_WEBAUTHN_DISPLAY_NAME: ENC[AES256_GCM,data:AZJ2bsWK4k2P22BA/g==,iv:dT0L4tPZTguoIh8X2PCbXxGegU+B5olT2zSSnljAgz4=,tag:exuQo/uEaNMb+9hmqJNiDA==,type:str]
    AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:hCVa6OdHleCbJyAJ7+nZqvEjx07z0aKZ0qjhUrjFRfj/JRNGmsHdD1Tqh8wpYV+2jagwsvxBuh99H7LKV77N1Q==,iv:UhfABGfnKZGKDsgd6+o3HBz0Hq8wVSFHbJhSupWOUik=,tag:1thEAza7Vcx0xpTOZGPLpw==,type:str]
    AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:y5RM0T4EFwDeRucObBeUy6RDt3so6I7+3VkWCYovlYuc6RvMJ537VClwQcmMckU+7850hcdTI6Hnu72znkfkIA==,iv:WRIE8plg23RgtmbWct6Sg+iy4AvAXlSeA0ntXYB1hvM=,tag:hkSq6ubiZT2PEDDyUUdZUA==,type:str]
    AUTHELIA_STORAGE_MYSQL_PASSWORD: ENC[AES256_GCM,data:/Z3de1ZSSqU=,iv:R7p6rkqn86P4H+vmAS4CNRoWv84YCMh38vP32hjPKO0=,tag:iZbLndAfQmzvt5CmFa7x0A==,type:str]
    AUTHELIA_NOTIFIER_SMTP_HOST: ENC[AES256_GCM,data:7PBuN7OJtrHwQYLR1pU+QA==,iv:3FNr08CurXvKh8CEHnoeoqe7nhlCmRxjCpMBx7PTlUU=,tag:X9Vkj1qsnjAFdUsGuiRriA==,type:str]
    AUTHELIA_NOTIFIER_SMTP_PORT: ENC[AES256_GCM,data:Xu7l,iv:72qJrnQl59/vuu0Esh+dcETa3DSJbD56AzAhdtX2XZM=,tag:uGhpLHBoo6AIbzkh6IQ+lQ==,type:str]
    AUTHELIA_NOTIFIER_SMTP_SENDER: ENC[AES256_GCM,data:VdyNQu2YSoYtRmVySbnO3y6DVlNhJaBW,iv:BT3xyR+6w7O1L/Xy25fTOIarhH3karZ2qCMh0lbEvuQ=,tag:KsCIbxJRrBlKCG5sF94Ahw==,type:str]
    AUTHELIA_NOTIFIER_SMTP_USERNAME: ENC[AES256_GCM,data:ln8eHpf2H/qouK5ZOjkM7L0=,iv:6GIdp+xgG3vTs8DesrK/Lp+cdYsoxquYUu0ucFKc8rc=,tag:7rCe/irahKihGYw0oBGKsQ==,type:str]
    AUTHELIA_NOTIFIER_SMTP_PASSWORD: ENC[AES256_GCM,data:oGRMGSJsLH7E64+c14Tld13I5I4=,iv:Bab+2SI7JRYKrHQudhDUc/KtJVpaH+1lCMTj46chSqU=,tag:uLQj+fuGE09c40P4Q58pcg==,type:str]
    AUTHELIA_NOTIFIER_SMTP_STARTUP_CHECK_ADDRESS: ENC[AES256_GCM,data:ZooJXHP6SQlE0zZPlIs=,iv:rRj1f6ujmVJBxsH/IqdhfyoUCFghHfyPAftcyFSOd0k=,tag:4f7j5CNPUCTfFl7fFSDSKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSTd1Zyt2M3JSWEVoc05u
            YUM5UEI4T1FJckZXMFhxbzVMTXhhUmpXdFhFCkN2Wk4zbWgwdGhCNWJKWks0VFVB
            QytGWDZZdjl5M0JlR3BIYkVhSXcyRmMKLS0tIDNUSml4Vy90Q2dhVkJKK3dxUWE0
            SS9VN2ZxLyswOVRPZnZyU3VZVTRKWHcKADlGaKifkIFscmMullu7kLXdIb/OiLFn
            E9PVwbqrNZx+UQ33gilrLKi0KT0yVNNzuGqWoRhYgaiZepx46V52ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-21T22:13:39Z"
    mac: ENC[AES256_GCM,data:oCfG1Qo75jhMK0ssInb9sr7CcBC1xgIQieF3j3Xfy0Qj+QT4pgVz3jgT4THoLsWLjGmKMLzfv5zT7AT8emCgdC96yMs46qwvmMtzKx2u3L2v8T7TNVl00NM7xRJ/ommxRr5StBLE7CJQC2geC3SZ0LYJj+pjELq8rqqkK8D66zo=,iv:tX9z7j3ASv1Q5dv/qZtm9q3YIDzi8zjXpZDmDQHXXyU=,tag:yUxpnARDbCtpm+vBkk+eOQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
