---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-secrets
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: thanos
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        secret-key: "{{ .AWS_SECRET_ACCESS_KEY }}"
        s3-endpoint: "{{ .S3_ENDPOINT }}"
  dataFrom:
    - extract:
        key: thanos
