---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbms-mysql-pvc
  namespace: dbms
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
