---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-datastore
  namespace: media
spec:
  storageClassName: media-datastore
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_ATLAS_NFS_SERVER}
    path: "${SECRET_ATLAS_NFS_ROOTDIR}/media"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-datastore
  namespace: media
spec:
  storageClassName: media-datastore
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
