---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-datastore
  namespace: media
spec:
  storageClassName: plex-datastore
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_ATLAS_NFS_SERVER}
    path: "/mnt/atlas/media"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-datastore
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: plex-datastore
  resources:
    requests:
      storage: 1Mi
