---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.jetstack.io/
      chart: cert-manager
      version: v1.8.0
      sourceRef:
        kind: HelmRepository
        name: jetstack-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    installCRDs: false
    webhook:
      enabled: true
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          # cpu: 15m
          memory: 64M
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53
      - --dns01-recursive-nameservers-only
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        prometheusInstance: monitoring
    resources:
      requests:
        cpu: 15m
        memory: 94M
      limits:
        # cpu: 15m
        memory: 132M
    cainjector:
      resources:
        requests:
          cpu: 15m
          memory: 183M
        limits:
          # cpu: 15m
          memory: 258M
