---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cloudflare-secrets.sops.yaml
  - helm-release.yaml
  - issuers
  - ddns
  - dashboard
  - prometheus-rules.yaml
