---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CONFIG_CLUSTER_NAME: main
  CONFIG_K8S_POD_CIDR: 10.40.0.0/16
  CONFIG_TIMEZONE: America/Toronto
  CONFIG_CERTIFICATE_ISSUER: letsencrypt-prod
  CONFIG_METALLB_IP_RANGE: 10.0.40.33-10.0.40.63
  CONFIG_SVC_TRAEFIK_ADDR: 10.0.40.33
  CONFIG_SVC_MINIO_ADDR: 10.0.40.34
  CONFIG_SVC_MYSQL_ADDR: 10.0.40.35
  CONFIG_SVC_POSTGRES_ADDR: 10.0.40.36
  CONFIG_SVC_QBITTORRENT_ADDR: 10.0.40.37
  CONFIG_SVC_VECTOR_AGGREGATOR_ADDR: 10.0.40.38
  CONFIG_SVC_LOKI_ADDR: 10.0.40.39
  CONFIG_SVC_REDIS_ADDR: 10.0.40.40
  CONFIG_SVC_MINIO_HADES_ADDR:
  CONFIG_SVC_PLEX_ADDR: 10.0.40.41
