---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dashy-code-server-secrets
  namespace: web-tools
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dashy-code-server
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
  data:
    - secretKey: id_rsa
      remoteRef:
        key: admin-user
        property: id_rsa
