---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lidarr-secrets
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lidarr
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
  dataFrom:
    - extract:
        key: lidarr
