apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-red-nfs-pv
  namespace: home
spec:
  storageClassName: node-red-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_SERVER}
    path: "${SECRET_NFS_ROOTDIR}/home/node-red"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-node-red-pvc
  namespace: home
spec:
  storageClassName: node-red-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
