---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-red-datastore
  namespace: home
  labels:
    app.kubernetes.io/name: &name node-red
    app.kubernetes.io/instance: *name
spec:
  storageClassName: node-red-datastore
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_ATLAS_NFS_SERVER}
    path: "${SECRET_ATLAS_NFS_ROOTDIR}/home/node-red"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-datastore
  namespace: home
  labels:
    app.kubernetes.io/name: &name node-red
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  storageClassName: node-red-datastore
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
