---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-datastore
  namespace: home
  labels:
    app.kubernetes.io/name: &name node-red
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
