apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secrets
    namespace: dbms
stringData:
    email: ENC[AES256_GCM,data:OrcaH8MaYve4wat/iaE=,iv:HwYDBBVCXGezYJ1ZUbvDri3kFMelynTLK527TDY/5kQ=,tag:l7CtDkGHLyHZaI75fTVTOA==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:o7djFJGZ3lyHuI0ufybUmw==,iv:Nhkq27/QZd+84tIkkbq3UU/8MQI08FXPn9tzuJDNylA=,tag:/rlXJevys2LTRNzJPFhKKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p28u8xjm5sf7jdavc8xsqtw7lxgscefxs7a5dtqszr2885xeputsh9y64y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeVpuU0JobmVrVU5ldGtY
            d1FwQTVsdFlvbitZUDN0UXkxN25QWTR0eGpnCi8wZWQ4YWxxc2w3RnprUnZ6bHEy
            NTZNU2pFWk9Wdm5DSVpRM0tlZFpKd2MKLS0tIC9BN1JkVTNUVVZpQm9iYnNiYlJn
            SDc0Mkh2ZE9ZRWFtTS9jV0VJVnhLTUUKjcK+2+vTD8uCRl2u4t9IwsCFWJb4gkju
            7RBPpWV5jp2BQKUHry9zCvuFJjtRiylARspQBp37UYtUkH3ypZ82bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-01T12:54:27Z"
    mac: ENC[AES256_GCM,data:BzQdBzXoBVPpHBCoCKKfh2sm1i1W4x0lv+3HTn/s+oguWC1fHJljQVYUrn21Q2bnKO8DWcAv5i/LC2IYKlpM0c/nfVSTk7ZSmFWXyjY/t48lVpahOIySTI7xhrErIx76kNiHovE9YRqIIkNiNoxQmeuiFdGDIZSNoNNzMBgnMGw=,iv:dN766j4IwtBoUxuPWIdwPARjOlqlDIV/6VIRjuIqFH8=,tag:UT5QLWJRaoFz+ZZjgA6pHQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
