---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-config
  namespace: dbms
  labels:
    app.kubernetes.io/name: &name pgadmin
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 100Mi
